require_relative '../node_modules/@capacitor/ios/scripts/pods_helpers'
platform :ios, '13.0'
use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor',          :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova',   :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
end

target 'PluginTests' do
  capacitor_pods
end

post_install do |installer|
  capacitor_pod_install(installer)
  assert_deployment_target(installer)
end
